---

- hosts: all
  gather_facts: False
  become: False

  tasks:
    - fail:
        msg: "student_number not defined"
      when: student_number is not defined


- hosts: tag_role_web
  gather_facts: False
  become: False

  tasks:
    - reboot:
      when: groups['tag_role_web'][student_number|int] == inventory_hostname


- hosts: tag_role_api
  gather_facts: False
  become: False

  tasks:
    - reboot:
      when: groups['tag_role_api'][student_number|int] == inventory_hostname

