---


- hosts: all
  gather_facts: False
  become: False

  tasks:
    - fail:
        msg: "student_number not defined"
      when: student_number is not defined


- hosts: "web-{{ student_number }}"
  gather_facts: False

  tasks:
    - reboot:


- hosts: "api-{{ student_number }}"
  gather_facts: False

  tasks:
    - reboot:

