---

- hosts: all
  gather_facts: False
  become: True

  tasks:
    - fail:
        msg: "student_number not defined"
      when: student_number is not defined


- hosts: tag_role_web
  gather_facts: False

  tasks:
    - lineinfile:
        path: /var/www/html/configure.php
        regexp: API_SERVER_PORT
        line: "define('API_SERVER_PORT','7000');"
      when: groups['tag_role_web'][student_number|int] == inventory_hostname


