---

- hosts: all
  gather_facts: False

  tasks:
    - fail:
        msg: "student_number not defined"
      when: student_number is not defined


- hosts: "web-{{ student_number }}"
  gather_facts: False
  become: True

  tasks:
    - name: Mystery
      lineinfile:
        path: /var/www/html/configure.php
        regexp: API_SERVER_PORT
        line: "define('API_SERVER_PORT','7000');"


