---

- hosts: all
  gather_facts: False
  become: False

  tasks:
    - fail:
        msg: "student_number not defined"
      when: student_number is not defined


- hosts: "web-{{ student_number }}"
  gather_facts: False
  become: False

  tasks:
    - name: Set deny all on web SG
      ec2_group:
        region: "{{ aws_region }}"
        name: "web-{{ student_number }}"
        description: "web-{{ student_number }}"
        vpc_id: "{{ ec2_vpc_id }}"
        group_id: "{{ ec2_security_group_ids }}"
        rules:
      delegate_to: localhost


- hosts: "api-{{ student_number }}"
  gather_facts: False
  become: False

  tasks:
    - name: Set deny all on api SG
      ec2_group:
        region: "{{ aws_region }}"
        name: "api-{{ student_number }}"
        description: "api-{{ student_number }}"
        vpc_id: "{{ ec2_vpc_id }}"
        group_id: "{{ ec2_security_group_ids }}"
        rules:
      delegate_to: localhost

